### ISSUE TITLE
Having class's name as a root key in JSON

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#10]
I think it will be useful to have an optional argument that places class's name as a first key in JSON. For example:
``` ruby
class Cat
  include Surrealist

  json_schema do
    { weight: String }
  end

  def weight
    '3 kilos'
  end
end

Cat.new.surrealize(include_root: true)
# => '{ "cat": { "weight": "3 kilos" } }'
```
A few things that have to be taken care of:
1. If `camelize: true` is passed to `#surrealize`, root should also be converted to camelBack.
2. Root key should not be placed inside nested objects.

**Comment by allcentury** [comment]
what would happen to a nested class, ie

```ruby
class Animal
  class Cat
  end
end
```
Would the root be `cat` or `cat_animal`? Also what json would it produce with a nested class?  `{ 'animal": { "cat": ... } }`

**Comment by nesaulov** [comment]
@allcentury that's a good point, thanks. I think that the least surprising way would be to have the following:
```ruby
class Animal
  class Cat
    include Surrealist

    json_schema do
      { breed: String }
    end

    def breed
      'Bengal'
    end
  end
end
Animal::Cat.new.surrealize(include_root: true)
# # => '{ "animal_cat": { "breed": "Bengal" } }'
```
But I would love to hear opinions on this question

**Comment by nesaulov** [comment]
Actually, I think that it would be better to have the last namespace as root key, e.g
```ruby
Animal::Cat.new.surrealize(include_root: true)
# # => '{ "cat": { "breed": "Bengal" } }'
```
And add another option to include namespaces:
```ruby
Animal::Cat.new.surrealize(include_namespaces: true)
# # => '{ "animal": { "cat": { "breed": "Bengal" } } }'
```
And maybe later add a feature to specify level of namespaces nesting, something like
```ruby
BusinessSystem::Core::Domain::Cashout::Reports::Withdraws.new.surrealize(include_namespaces: true, namespace_nesting_level: 3)
# '{ "cashout": { "reports": { "withdraws": { "id": 3, "amount": 345, ... } } } }'
```
