### ISSUE TITLE
Unable to override method in 1.2

### ISSUE THREAD

**Issue by tycooon** [nesaulov/surrealist#108]
```ruby
gem "surrealist", "1.2.0"
require "surrealist"

class KekSerializer < Surrealist::Serializer
  json_schema do
    {
      kek: String,
      cheburek: String,
    }
  end

  def kek
    "kek"
  end

  def cheburek
    "cheburek"
  end
end

class A
  def kek
    "smth"
  end
end

kek = A.new
p KekSerializer.new(kek).build_schema # => {:kek=>"smth", :cheburek=>"cheburek"}
```

The output was `{:kek=>"kek", :cheburek=>"cheburek"}` in version 1.1.2.

**Comment by nesaulov** [comment]
Yes that's a bug, thanks for reporting @tycooon

**Comment by gjhenrique** [comment]
It seems the culprit is from https://github.com/nesaulov/surrealist/pull/103/commits/d891ef1950e3f90794db2e95951a2a697d07091c

Do you mind if I take a look at that @nesaulov?

**Comment by nesaulov** [comment]
@gjhenrique sure, I wanted to fix that but I can't really find the time still. Thank you!
