### ISSUE TITLE
Delegate surrealization to parent class

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#11]
Considering this example:
``` ruby
class Parent
  include Surrealist

  json_schema do
    { name: String }
  end

  def name
    'Parent'
  end
end

class Child < Parent
  def name
    'Child'
  end
end
```
If we surrealize `Parent`, everything is fine:
`Parent.new.surrealize # => '{ "name": "Parent" }'`
But if we surrealize `Child`, error is thrown:
``` ruby
Child.new.surrealize
# => Surrealist::UnknownSchemaError: Can't serialize Child - no schema was provided.
```

I guess it would be useful to have a class method that would delegate surrealization to specified class, something like:
``` ruby
class Child < Parent
  
  delegate_surrealization_to Parent
  
  def name
    'Child'
  end
end
Child.new.surrealize # => '{ "name": "Child" }'
```

**Comment by AlessandroMinali** [comment]
I will take a look at this

**Comment by nesaulov** [comment]
@AlessandroMinali alright, thanks!
