### ISSUE TITLE
Can't redefine object method with inheritance

### ISSUE THREAD

**Issue by kolasss** [nesaulov/surrealist#115]
If parent serializer redefines object's method it's not invoked in child serializer and calls object's method (same behaviour with modules)

```
require 'surrealist'

class User
  def first
    2
  end
end

class User::BaseSerializer < Surrealist::Serializer
  def first
    object.first * 2
  end
end

class UserSerializer < User::BaseSerializer
  json_schema { { first: Integer } }
end

user = User.new

p UserSerializer.new(user).build_schema
# prints {:first=>2} 
# should be {:first=>4} 

```
I believe this is because of `false` argument for `instance_methods` [here](https://github.com/nesaulov/surrealist/blob/master/lib/surrealist/value_assigner.rb#L50)
Bug or feature?

**Comment by nesaulov** [comment]
Hey, thank you for reporting this, it is a bug, that was introduced while fixing [this.](https://github.com/nesaulov/surrealist/pull/110#discussion_r199534553)
Right now I am working on #114, would you like to introduce a PR to help me out with this bug?
