### ISSUE TITLE
Collection serialization

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#12]
I guess we need to have a way to serialize collections. Let's take AR for example:
```ruby 
class User < ActiveRecord::Base
  include Surrealist

  json_schema do
    { id: Integer, name: String }
  end
end
```
It would be convenient to have something like
```ruby
Surrealist.surrealize_collection(User.all, include_root: true)
# => '{ "users": [ { "id": 1, "name": "John" }, { "id": 2, "name": "Chris" } ... ] }'
```
We also need to take care of other ORMs and mappers, e.g. [sequel](http://sequel.jeremyevans.net/), [rom](http://rom-rb.org/).

**Comment by nesaulov** [comment]
Or maybe #13 will solve this problem.

**Comment by AlessandroMinali** [comment]
I think this is done? @nesaulov

**Comment by nesaulov** [comment]
I will add specs for ROM, Sequel and DM and then close it.

**Comment by nesaulov** [comment]
Closing this.
