### ISSUE TITLE
Nil values for Boolean type

### ISSUE THREAD

**Issue by AllanQ** [nesaulov/surrealist#126]
Hi, @nesaulov.

It would be nice to allow nil values for attributes of boolean type.

```
class User
  include Surrealist

  json_schema do
    {
      admin: Bool,
    }
  end
end
```

```
Surrealist::InvalidTypeError:
       Wrong type for key `admin`. Expected Bool, got NilClass.
```

**Comment by TrumpClone** [comment]
Type definition means `only this type and it's subtypes`
If you want to use `nil or type` - you should use `Any`. Or => you should make a PR with a new type definition dsl ;)

**Comment by 0exp** [comment]
@TrumpClone +1
Exactly

**Comment by noexclusive** [comment]
Wowowow. Hey. You are liers: only `Bool` cant work with `nil`s. Another types can work with it.
So, @nesaulov! You must fix this ASAP

**Comment by nesaulov** [comment]
Yep, you are right
