### ISSUE TITLE
ActiveRecord_Relation serialization

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#13]
Right now objects that are created from methods that return `ActiveRecord_Relation` (like `#where`) can not be surrealized:
```
User.where(id: 3).surrealize
# => NoMethodError: undefined method `surrealize' for #<User::ActiveRecord_Relation:0x007f90ae569758>
```
We need to have some kind of schema delegation to the initial object here.

**Comment by nesaulov** [comment]
I guess we have two ways here:
1. Monkey-patch `ActiveRecord_Relation` so it has `#surrealize` on an instance.
2. Force users to use `Surrealist#surrealize(instance)` directly.
I personally prefer second option.

**Comment by AlessandroMinali** [comment]
Could we just map back the surrealization of each element:

```
    # something like this 🤷🤷 ¯\_(ツ)_/¯
    def surrealize(instance:, camelize:, include_root:)
      instance.map { |i| surrealize(i,camelize, include_root) } if instance.respond_to?(:each) #
      ::JSON.dump(build_schema(instance: instance, camelize: camelize, include_root: include_root))
    end
```

I think this is similar behaviour as ActiveModel::Serializer.

**Comment by nesaulov** [comment]
@AlessandroMinali yeah, you are right, it's a third option and it looks alright. I'll think about it for a while.

**Comment by nesaulov** [comment]
Actually, there is the same downside as in the first option - we'll have to monkey-patch `Enumerable` and else, because otherwise `NoMehtodError` is thrown:
```ruby
User.where(id: 3).surrealize
# => NoMethodError: undefined method `surrealize' for #<User::ActiveRecord_Relation:0x007f90ae569758>
```

**Comment by AlessandroMinali** [comment]
Hmm, right.

```
x = User.where(id: 1)
pp x.ancestors
```
 Shows Surrealist and Instance Methods but for some the methods haven't been included? Not really sure what's going on there.

I guess a simple solution is to introduce a new method like mentioned in the other issue which is just a wrapper to call"
```
return instance.map { |i| surrealize(i,camelize, include_root) } if instance.respond_to?(:each) #
```

Would be nice if it just `worked` though without a separate method.

**Comment by AlessandroMinali** [comment]
Here are [monkey-patch attempt](https://github.com/nesaulov/surrealist/compare/master...AlessandroMinali:monkey-surrealize?expand=1) and a [#surrealize_collection methods](https://github.com/nesaulov/surrealist/compare/master...AlessandroMinali:collection-method?expand=1)  WIPs to compare.

Both have specs for AR, ROM, Datamapper and Sequel.

**Comment by nesaulov** [comment]
thanks, @AlessandroMinali! I think `#surrealize_collection` way is much better than monkey-patching, so we can continue to work on that one. Am I right that the API you are planning to introduce is `Surrealist.surrealize_collection(collection)`?

**Comment by AlessandroMinali** [comment]
Yes, that's correct @nesaulov, with the ability to specific camelize and include root etc. if they so choose.
