### ISSUE TITLE
`root_key` optional argument

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#24]
Right now `Surrealist` has optional `include_root` key word argument that works like this:
```ruby
module Animal
  class Cat
    include Surrealist

    json_schema do
      { weight: String }
    end

    def weight
      '3 kilos'
    end
  end
end

Animal::Cat.new.surrealize(include_root: true)
# => '{ "cat": { "weight": "3 kilos" } }'
```
It takes the bottom-level class name and sets it as a root key to resulting JSON. I think we need yet another kwarg: `root:`, so that JSON can be wrapped into any key that user provides. I imagine API like this:
```ruby
Animal::Cat.new.surrealize(root: :kitten)
# => '{ "kitten": { "weight": "3 kilos" } }'
Animal::Cat.new.surrealize(root: 'kitten')
# => '{ "kitten": { "weight": "3 kilos" } }'
```
It should work without `include_root` and `include_namespaces`. 
And when both `include_root || include_namespaces` and `root` are passed, the hash that is returned from `include_root` or `include_namespaces` should be wrapped into `root`:

```ruby
Animal::Cat.new.surrealize(include_root: true, root: :kitten)
# => '{ "kitten": { "cat": { "weight": "3 kilos" } } }'
Animal::Cat.new.surrealize(include_namespaces: true, root: 'kitten')
# => '{ "kitten": { "animal": { "cat": { "weight": "3 kilos" } } } }'
```

**Comment by chrisatanasian** [comment]
I will take this one.

**Comment by nesaulov** [comment]
@chrisatanasian alright, thanks! Feel free to ask questions.

**Comment by chrisatanasian** [comment]
@nesaulov Here is my PR: https://github.com/nesaulov/surrealist/pull/32/

**Comment by nesaulov** [comment]
@chrisatanasian thanks!
