### ISSUE TITLE
DataMapper Integration

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#46]
We need specs to make sure that Surrealist works fine with DataMapper objects.

**Comment by nesaulov** [comment]
Actually, I don't know if this is even necessary, as DataMapper seems to be [unmaintained for several years](https://github.com/datamapper/dm-core/graphs/contributors) now. @AlessandroMinali what do you think?

**Comment by AlessandroMinali** [comment]
Yea, that makes sense. I think I only originally included it my specs cause I had made a habit of using for small projects years ago.

**Comment by nesaulov** [comment]
Closing then.
