### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#63]
I think it's time to release 1.0.0 version of this gem. I will write some docs on how to work with ORMs and the nuances that should be kept in mind when doing so. Unfortunately, I have no time right now to write benchmarks, I guess I'll do that a bit later. I will also write a blog post about what's new in 1.0.0. @AlessandroMinali is there anything that should be done before release from your point of view?

**Comment by AlessandroMinali** [comment]
I can't really think of anything other the benchmarks. Seems to be in a good spot right now and provides quite a bit of functionality.

Do you have a roadmap for after 1.0.0?

**Comment by nesaulov** [comment]
I guess I'll do benchmarking before release.
Concerning roadmap: not yet, we have two issues to think about: [having multiple serializers](https://github.com/nesaulov/surrealist/issues/59#issuecomment-357765520) and [DSL for context in serializer](https://github.com/nesaulov/surrealist/pull/61#issuecomment-357287239)
I have also thought about adding some kind of caching/memoization.

**Comment by nesaulov** [comment]
@AlessandroMinali I am going to add [Oj](https://github.com/ohler55/oj) dependency. It's not that good to have a dependency, but on the other hand `Oj` is 2.5x faster than stdlib `JSON`.

**Comment by nesaulov** [comment]
Released! 🎉
