### ISSUE TITLE
Multiple serializers for one model

### ISSUE THREAD

**Issue by nulldef** [nesaulov/surrealist#65]
Hi all!
As I already suggested in #59, we can use `tag` option for splitting serializers. I propose this API:
```ruby
class HumanSerializer < Surrealist::Serializer
  json_schema do
    { name: String, name_length: Integer }
  end

  def name_length
    name.length
  end
end

class SmallHumanSerializer < Surrealist::Serializer
  json_schema do
    { name: String }
  end
end

class Human
  include Surrealist

  attr_reader :name

  surrealize_with HumanSerializer # default
  surrealize_with SmallHumanSerializer, tag: :small

  def initialize(name)
    @name = name
  end
end
```

```ruby
# default behaviour
Human.new('John').surrealize(camelize: true)
# => '{"name": "John", "nameLength": 4}'

# using tags
Human.new('John').surrealize(camelize: true, tag: :small)
# => '{"name": "John"}'
```

I can realize this functionality and I know that it will be very useful feature.

**Comment by AlessandroMinali** [comment]
I like this option and the PR but I think we can do better than `tag`.

I think `as` works for both setting and using.
We could differentiate using by making the option `with`.
@nesaulov ?

Just a minor nitpick.

**Comment by nesaulov** [comment]
@AlessandroMinali I don't think `with` will do, it just looks bad (two withs): 
``` ruby
class Something
  include Surrealist
  
  surrealize_with SomethingSerializer, with: :api
end
```
`as` seems okay, but honestly I don't consider it to be better than `tag`, I think `tag` is more semantically descriptive in our case.

```ruby
User.find(34).surrealize(as: :api)
User.find(34).surrealize(tag: :api)
```
