### ISSUE TITLE
DSL for serializer contexts

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#67]
As @AlessandroMinali [suggested](https://github.com/nesaulov/surrealist/pull/61#issuecomment-357287239) in #61:

> Maybe this could be another DSL (at the cost of adding more complexity for a low use case, maybe not worth)?

Right now we have to access context variables via `context[:variable_name]`. Suggested is the following DSL:

```ruby
class IncomeSerializer < Surrealist::Serializer
  json_schema { { amount: Integer } }
  serializer_context :current_user, :something, :else
  
  def amount
    current_user.guest? ? 100000000 : object.amount
  end
end
```

I suggest to implement this feature (if we decide to implement it in the first place) after 1.0.

**Comment by nulldef** [comment]
Sorry, my mistake )

**Comment by nulldef** [comment]
It seems not cool, here we write `json_schema`, there - `serializer_context`. Maybe we should use `json_context`?

**Comment by AlessandroMinali** [comment]
I think that still gets the point across, I don't feel strongly about either. Should we add an method alias here as well for a plural version `:json_contexts` to be dev friendly?

**Comment by nesaulov** [comment]
I think that `json_context` is a bit misleading here. It's a context which is available inside a serializer instance, not inside JSON object. I am with the plural version idea though.
