### ISSUE TITLE
Change API for multiple serializers

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#71]
What we have right now:
```ruby
class Something
  include Surrealist
  surrealize_with SomethingSerializer
  surrealize_with SomethingShortSerializer, tag: :short
end

Something.new.surrealize
Something.new.surrealize(tag: :short)
```
This `tag` option still bothers me, I think passing `tag` as an option is not semantically correct here. Specifying a serializer with `tag` is alright, but serializing with `tag` seems wrong. I suggest having
`Something.new.surrealize(via: :short)` or `Something.new.surrealize(using: :short)` or `Something.new.surrealize(serializer: :short)` or `Something.new.surrealize(format: :short)` or  something else.

**Comment by nesaulov** [comment]
@AlessandroMinali @nulldef what do you think would be the best option here?

**Comment by nesaulov** [comment]
Personally I prefer `via` or `format`.

**Comment by nulldef** [comment]
We can try using `for` keyword.
`format` is terrible I think. And about `via` - maybe It will be more semantically correct in some cases, but not in mostly cases.

**Comment by nesaulov** [comment]
Yes, maybe you are right and `for` is a good option since the most cases where one would need multiple serializers would be a web application with a number of presentation points of some models. Something like
```ruby
class Post < ActiveRecord::Base
  include Surrealist
  
  surrealize_with PostSerializer
  surrealize_with PostPreviewSerializer, tag: :preview
  surrealize_with PostApiSerializer, tag: :api
  surrealize_with PostFrontendSerializer, tag: :frontend
end
```
In this case the most appropriate way to specify serialiser would be to specify the goal of serialization.
```
Post.find(42).surrealize(for: :preview)
Post.find(42).surrealize(for: :api)
Post.find(42).surrealize(for: :frontend)
```
`Post.find(42).surrealize(via: :preview)` doesn't seem quite right in this case. So the question is whether this kind of context would be primary for the most of the use cases of this feature. @AlessandroMinali what do you think?

**Comment by AlessandroMinali** [comment]
`:for` seems fine to me.

I guess one way to cover all use cases is to be pedantic and just call the option `:serializer`. That leaves nothing to the imagination and is pretty dry about what is going on/being passed. In that case I'd still argue for `:as` to set the alias.

If the user sets a _tag_ but then still wants to be explicit and call the actual serializer by the constant are we going to allow that?
i.e.:
```ruby
Something.new.surrealize(tag: :short)
Something.new.surrealize(tag: SomethingShortSerializer) 
```

**Comment by nesaulov** [comment]
I guess we will provide the option to specify the serialiser class with
`Post.find(42).surrealize(serializer: PostPreviewSerializer)`. And for symbols let's leave `for`:
`Post.find(42).surrealize(for: :preview)`
