### ISSUE TITLE
Default options

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#76]
I think of having a possibility to define default options for serialization. Like [Oj](https://github.com/ohler55/oj) has. For example, for most of applications camel case conversions are either true or false for _all_ endpoints. I suggest API to be as simple as follows:

```ruby
Surrealist.default_options = { camelize: true, include_root: true }
```

@AlessandroMinali @nulldef what do you think?

**Comment by nulldef** [comment]
Yes, I think we have to provide default options definition.
I can suggest following API:
```ruby
Surrealist.config do |c|
  c.camelize = true
  c.include_root = true
end
```

What do you think?

**Comment by nesaulov** [comment]
@nulldef and what's the argumentation behind this API? I mean, why do you consider having a block with setters to be more preferable than just a hash?

**Comment by AlessandroMinali** [comment]
Rails for example allows this for a lot of it's configs and initializers so it is a common pattern to let the developer decide what style. Basically allow for both.

The difference would be an extra `:block given?` in processing.

**Comment by nesaulov** [comment]
I guess @AlessandroMinali is right on this, so the API should look like this:
```ruby
Surrealist.config do |config|
  config.camelize = true
  # ...more configs
end
# or
Surrealist.config = { camelize: true, ... }
```
