### ISSUE TITLE
conditional tags for json_schema

### ISSUE THREAD

**Issue by briu** [nesaulov/surrealist#86]
Currently, if I want to serialize only some fields from a serializer(for example for authorization purposes) I do it like this:

```ruby
module SerializerMixin
  def first_field
    []
  end
end

class CompositeSerializer < Surrealist::Serializer
  include SerializerMixin

  json_schema do
    { first_field: Array, second_field: Hash, third_field: String }
  end

  def second_field
    {}
  end

  def third_field
    "awesome issue"
  end
end

class GuestSerializer < Surrealist::Serializer
  include SerializerMixin

  json_schema do
    { first_field: Array }
  end
end

GuestSerializer.new(object).build_schema
```

I think it would be great, if we can use one serializer with different json schemas

```ruby
class CompositeSerializer < Surrealist::Serializer
  json_schema do
    { first_field: Array, second_field: Hash, third_field: String }
  end
 
  json_schema(:guest_user) do
    { first_field: Array }
  end

  def first_field
    []
  end

  def second_field
    {}
  end

  def third_field
    "awesome issue"
  end
end

CompositeSerializer.new(object).build_schema(:guest_user)
```

**Comment by nesaulov** [comment]
Looks good to me. @AlessandroMinali @nulldef what do you think?

**Comment by nulldef** [comment]
I think it is useless feature, 'cause we already have multiple serializers and this case can be solved via inheritance.

**Comment by nesaulov** [comment]
Yeah, I guess @nulldef is right about this. Placing different schemas in one class can lead to creating a god-object and introduce difficulties in supporting and changing it later on. Closing this for now, but thanks for proposal, @briu
