### ISSUE TITLE
Serialize from hash

### ISSUE THREAD

**Issue by glaucocustodio** [nesaulov/surrealist#96]
Suppose I have:

```ruby
class Foo
  include Surrealist
  json_schema do
    { foo: String }
  end
end
```
I can't serialize passing a hash (because the gem expect methods):
```ruby
Foo.new({ foo: "bar" }).surrealize # crash!
```
Do you plan add support for hash? I've created the thin wrapper below and it works:
```ruby
class HashBased
  include Surrealist

  attr_reader :hash

  def initialize(hash = {})
    @hash = hash.deep_symbolize_keys
  end

  def method_missing(method_name, *args)
    if hash.key?(method_name)
      hash[method_name]
    else
      super
    end
  end

  def respond_to_missing?(method_name, _include_private = false)
    hash.key?(method_name)
  end
end
```
```ruby
class Foo < HashBased
  json_schema do
    # same as before
  end
end
```
```ruby
Foo.new({ foo: "bar" }).surrealize # now it works!
```
With a simple piece of code like that we can open a bunch of new possibilities.

**Comment by nesaulov** [comment]
@glaucocustodio, thank you, I guess that's a good feature to have, I would be glad accepting a PR. The only thing to keep in mind is that we don't want to pollute the `Surrealist::Builder` class, as it's already quite complex. I suggest having a separate class, a `HashBuilder` for example, which accepts only hashes and validates them directly, not based on `method_missing`. There will also be a different (and easier) way to validate hash schema, something like
```ruby
hash.keys.length == schema.keys.length
hash.keys.map(&:to_sym).sort == schema.keys.sort
```
 And we will also need tests covering different cases, apparently.

**Comment by glaucocustodio** [comment]
Using my wrapper for hash, I just needed to change the `check_for_ar` method like below to support hash validation:

```ruby
def check_for_ar(schema, instance, key, value)
  if ar_collection?(instance, key)
    construct_collection(schema, instance, key, value)
  else
    ins = if instance.respond_to?(key)
        instance.send(key)
      elsif instance.is_a?(Hash)
        instance[key]
      else
        instance
      end
    call(value, ins)
  end
end
```

**Comment by nesaulov** [comment]
You see, I don't think that 4 if statements in one method is a good thing at all. And the semantics are broken here - why would we check for active record if we are just serializing a hash

**Comment by glaucocustodio** [comment]
You are right, this code is not very good. I need to take some time to create the HashBuilder.

**Comment by nesaulov** [comment]
Closing this due to #106
