### ISSUE TITLE
Easy access to defined schema and schema sample

### ISSUE THREAD

**Issue by glaucocustodio** [nesaulov/surrealist#97]
Suppose we have the following code:
```ruby
class MySerializer
  include Surrealist
  json_schema do
    { name: String, age: Int }
  end
end
```
```ruby
get '/foo' do
  # returns json using MySerializer
  present AnyClass.get_data(params), with: MySerializer 
end
```
In my request test I want to test the api without overtesting `AnyClass`, so I mock the return of `get_data`:
```ruby
it do
  expect(AnyClass).to receive(:get_data).and_return(data)
  get '/foo'
end
```
the `data` variable has to match the schema defined in `MySerializer`, so, I created a piece of code that generates a hash (because I am using my hack to accept hash) based on my defined schema (set with `json_schema`) to be DRY (so I dont have to mock manually).

I had to do `instance_variable_get('@__surrealist_schema')` to get the defined schema..

What if we could do just `MySerializer.defined_schema` to get the defined schema?

Going further..

What if we could do just `MySerializer.schema_sample` to get a sample of the schema, something like: 
```ruby
{ name: "", age: 0 }
```
Then I could do this in my test instead of having to define by myself a schema matching hash for the mock:
```ruby
let(:data) { MySerializer.schema_sample } 
```

Full demo: https://gist.github.com/glaucocustodio/85217a4e153407f053ae0cb60144a189

**Comment by nesaulov** [comment]
Hey @glaucocustodio, thank you for this proposal. I have been thinking myself about some kind of a schema-testing instrument, but I had some kind of a rspec/minitest matcher in mind, like
```ruby
expect(JSON.parse(response)).to match_schema_of(MySerializer)
```
But I guess a method will also do for some cases, so I would be glad accepting a PR with it's implementation. And Rspec/MiniTest matcher would be just awesome.

Concerning schema samples, I think there's a lot of things to consider here, because there are more types than just `Integer`, `String` or `Bool`. I think we should create a separate issue to discuss this proposal, what do you think?

**Comment by glaucocustodio** [comment]
We need to think about this matcher because `JSON.parse(response)` convert hash keys to string and the schema very likely will be as symbol.

Should we use `deep_stringify_keys` or `deep_symbolize_keys` from ActiveSupport ou should we implement by ourselves?

**Comment by glaucocustodio** [comment]
Hi @nulldef, I don't want to test the schema with requests spec.

I want to test only the endpoint, so I mock the implementation class behind it, but the serializer in use, expects to receive a valid json schema. To avoid my request spec to know about the schema, would be nice if I could generate a sample schema using `MySerializer.schema_sample` by example.

**Comment by nulldef** [comment]
@glaucocustodio 
if we add a method like `schema_sample` - request spec will be known about the schema.

> I want to test only the endpoint

What does it mean? That endpoint returns 200OK?

**Comment by glaucocustodio** [comment]
I dont see how the endpoint will not be bounded to the response schema.

Either I use something to "automate" my work or I have to mock one manually (because the serializer validates the given schema).

> What does it mean?
Status code, content-type, response body matching the class return being called.

**Comment by nulldef** [comment]
I'm sure that `expect(response.body).to eq(MySerializer.defined_schema)` is enough

**Comment by glaucocustodio** [comment]
To get a `response.body` matching the `defined_schema` I have to mock one to pass to `MySerializer`.

I want to ease this mocking, by not having to write one by myself, instead, getting one with `schema_sample`.

**Comment by nulldef** [comment]
Sorry, but I can't understand why you **have to** mock `defined_schema` method.

**Comment by nesaulov** [comment]
Hey, @glaucocustodio are you planning to do something with this issue? Or is something blocking it?

**Comment by nesaulov** [comment]
I have given it a thought and I guess no, it does not make sense to add this to the surrealist gem itself. Maybe later we can implement some kind of surrealist-rspec with `schema_sample` and `expect(...).to match_schema_of(Serializer)`.
I will close this for now, feel free to reopen it if you have any questions.
